### ISSUE TITLE
ANSI escape codes does not work on Windows

### ISSUE THREAD

**Issue by GleisonOliveira** [codedge-llc/scribe#22]
I'm trying use a  console table, but I receive the following error: 
```
Pane requires ANSI escape codes to work. Enable? (Yn) y
** (EXIT from #PID<0.93.0>) an exception was raised:
    ** (ErlangError) Erlang error: :enoent
        (elixir 1.13.2) lib/system.ex:1044: System.cmd("tput", ["lines"], [])
        (pane 0.4.1) lib/viewer.ex:128: Pane.Viewer.max_lines/0
        (pane 0.4.1) lib/viewer.ex:42: Pane.Viewer.init/1
        (stdlib 3.16.1) gen_server.erl:423: :gen_server.init_it/2
        (stdlib 3.16.1) gen_server.erl:390: :gen_server.init_it/6
        (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

Additional info
Os: Windows 10
Prompt: cmd

**Comment by hpopp** [comment]
So better late than never, I casually fixed this while updating the `pane` library that scribe depends on. 🚀 

https://github.com/codedge-llc/pane/releases/tag/v0.5.1
